blueprint:
  name: Licht bei Bewegung und Dunkelheit (2 Lux-Sensoren)
  description: >
    Schaltet ein Licht ein, wenn ein Bewegungsmelder auslöst
    und beide Helligkeitssensoren unter den definierten Schwellen liegen.
  domain: automation
  input:
    motion_sensor:
      name: Bewegungsmelder
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Licht / Schalter
      selector:
        target:
          entity:
            domain:
              - light
              - switch
    lux_sensor_1:
      name: Helligkeitssensor 1
      selector:
        entity:
          domain: sensor
    lux_sensor_2:
      name: Helligkeitssensor 2
      selector:
        entity:
          domain: sensor
    lux_threshold_1:
      name: Schwellwert Sensor 1 (Lux)
      default: 2
      selector:
        number:
          min: 0
          max: 1000
          mode: box
    lux_threshold_2:
      name: Schwellwert Sensor 2 (Lux)
      default: 10
      selector:
        number:
          min: 0
          max: 1000
          mode: box
    motion_duration:
      name: Mindest-Bewegungsdauer (s)
      default: 1
      selector:
        number:
          min: 0
          max: 60
          mode: slider

mode: single

variables:
  lux_sensor_1: !input lux_sensor_1
  lux_sensor_2: !input lux_sensor_2
  lux_threshold_1: !input lux_threshold_1
  lux_threshold_2: !input lux_threshold_2

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    for:
      seconds: !input motion_duration

condition:
  - condition: template
    value_template: >
      {{ states(lux_sensor_1) | float(999) < (lux_threshold_1 | float(999)) }}
  - condition: template
    value_template: >
      {{ states(lux_sensor_2) | float(999) < (lux_threshold_2 | float(999)) }}

action:
  - service: homeassistant.turn_on
    target: !input light_target
