blueprint:
  name: Licht bei Bewegung und (optional) Dunkelheit
  description: >
    Schaltet ein Licht ein, wenn mindestens ein Bewegungsmelder / Occupancy-Sensor auslöst.
    Bis zu 2 zusätzliche Bewegungs-/Belegungssensoren optional.
    Bis zu 2 Helligkeitssensoren optional.
  domain: automation
  input:
    motion_sensor_1:
      name: Bewegungsmelder 1 (Pflicht)
      selector:
        entity:
          domain: binary_sensor
          # keine device_class → zeigt alle binary_sensor an
    motion_sensor_2:
      name: Bewegungsmelder 2 (optional)
      default: ""
      selector:
        entity:
          domain: binary_sensor
    motion_sensor_3:
      name: Bewegungsmelder 3 (optional)
      default: ""
      selector:
        entity:
          domain: binary_sensor

    motion_duration:
      name: Mindest-Bewegungsdauer (Sekunden)
      default: 1
      selector:
        number:
          min: 0
          max: 120
          mode: slider

    lux_sensor_1:
      name: Helligkeitssensor 1 (optional)
      default: ""
      selector:
        entity:
          domain: sensor
    lux_threshold_1:
      name: Schwellwert Sensor 1 (Lux)
      default: 2
      selector:
        number:
          min: 0
          max: 2000
          mode: box

    lux_sensor_2:
      name: Helligkeitssensor 2 (optional)
      default: ""
      selector:
        entity:
          domain: sensor
    lux_threshold_2:
      name: Schwellwert Sensor 2 (Lux)
      default: 10
      selector:
        number:
          min: 0
          max: 2000
          mode: box

    light_target:
      name: Licht / Schalter
      description: Das Gerät, das eingeschaltet werden soll.
      selector:
        target:
          entity:
            domain:
              - light
              - switch

mode: single

variables:
  motion_sensor_1: !input motion_sensor_1
  motion_sensor_2: !input motion_sensor_2
  motion_sensor_3: !input motion_sensor_3
  lux_sensor_1: !input lux_sensor_1
  lux_sensor_2: !input lux_sensor_2
  lux_threshold_1: !input lux_threshold_1
  lux_threshold_2: !input lux_threshold_2

trigger:
  - platform: state
    entity_id: !input motion_sensor_1
    to: "on"
    for:
      seconds: !input motion_duration

  - platform: state
    entity_id: !input motion_sensor_2
    to: "on"
    for:
      seconds: !input motion_duration
    enabled: "{{ motion_sensor_2 != '' }}"

  - platform: state
    entity_id: !input motion_sensor_3
    to: "on"
    for:
      seconds: !input motion_duration
    enabled: "{{ motion_sensor_3 != '' }}"

condition:
  - condition: template
    value_template: >
      {% set s1 = lux_sensor_1 %}
      {% set s2 = lux_sensor_2 %}
      {% set v1 = states(s1)|float(999) %}
      {% set v2 = states(s2)|float(999) %}
      {% if s1 == '' and s2 == '' %}
        true
      {% elif s1 != '' and s2 == '' %}
        {{ v1 < (lux_threshold_1 | float(999)) }}
      {% elif s1 == '' and s2 != '' %}
        {{ v2 < (lux_threshold_2 | float(999)) }}
      {% else %}
        {{ v1 < (lux_threshold_1 | float(999)) and v2 < (lux_threshold_2 | float(999)) }}
      {% endif %}

action:
  - service: homeassistant.turn_on
    target: !input light_target
